repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/pre-commit/misc-hooks
    rev: v1.0.0
    hooks:
      - id: check-java

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.0.0
    hooks:
      - id: maven-linter
