services:
  between-products-api-test:
    build: .
    ports:
      - "5000:5000"
      - "9090:9090"
    environment:
      - PRODUCT_API_BASE_URL=http://simulado:80
    networks:
      - backenddevtest_default

networks:
  backenddevtest_default:
    external: true
