spring:
  application:
    name: products-api-test
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  openapi:
    file: classpath:openapi.yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com.between.products: INFO
server:
  port: 5000
product:
  api:
    baseUrl: http://localhost:3001
    timeouts:
      connect: 10000
      read: 10000
      write: 10000
      response: 10000
resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 30
        minimum-number-of-calls: 10
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - io.netty.handler.timeout.ReadTimeoutException
