spring:
  application:
    name: products-api-test
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com.between.products: INFO
server:
  port: 5000
product:
  api:
    baseUrl: ${PRODUCT_API_BASE_URL:http://simulado:80}
resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 30
        minimum-number-of-calls: 10
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
