spring:
  application:
    name: products-api-test
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com.between.products: INFO
server:
  port: 5000
product:
  api:
    baseUrl: ${PRODUCT_API_BASE_URL:http://simulado:80}
