spring:
  application:
    name: products-api-test
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  openapi:
    file: classpath:openapi.yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com.between.products: INFO
server:
  port: 5000
product:
  api:
    baseUrl: ${PRODUCT_API_BASE_URL:http://simulado:80}
    timeouts:
      connect: 2000
      read: 2000
      write: 2000
      response: 2000
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 30
        minimumNumberOfCalls: 10
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        ignoreExceptions:
          - com.between.products.domain.product.ProductNotFoundException
    instances:
      productSimilarIdsCB:
        baseConfig: default
      productDetailCB:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - com.between.products.domain.product.ProductRequestException
    instances:
      productSimilarIdsRetry:
        baseConfig: default
      productDetailRetry:
        baseConfig: default
        waitDuration: 100ms
  ratelimiter:
    instances:
      similarProductsLimiter:
        timeoutDuration: 1s
        limitRefreshPeriod: 500ms
        limitForPeriod: 150
